---
# Needed for add-apt-repository
#- name: Add repository key
#  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886 state=present
#  tags:
#    - apt
#

- name: Add Java repository
  apt_repository: repo="ppa:openjdk-r/ppa" state=present update_cache=yes
  tags:
    - apt

